{% set version = "2.60" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-epi
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Epi_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Epi/Epi_{{ version }}.tar.gz
  sha256: 29d6d91a7a0f04369852738fce009b3aefa59c65380174b6eec24ba7046aec57

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    # The libstdc++.dll provided in libstdcxx v15.1.0 build h904f734_2
    # is missing `_ZSt21ios_base_library_initv`.
    # see: conda-forge/ctng-compilers-feedstock#174
    - libstdcxx !=14.3.0,!=15.1.0  # [win]
  host:
    - r-base
    - r-mass
    - r-matrix
    - r-cmprsk
    - r-data.table
    - r-dplyr
    - r-etm
    - r-magrittr
    - r-mgcv
    - r-numderiv
    - r-plyr
    - r-survival
    - r-zoo
  run:
    - r-base
    - r-mass
    - r-matrix
    - r-cmprsk
    - r-data.table
    - r-dplyr
    - r-etm
    - r-magrittr
    - r-mgcv
    - r-numderiv
    - r-plyr
    - r-survival
    - r-zoo
  run_constrained:
    - libstdcxx !=14.3.0,!=15.1.0           # [win]

test:
  commands:
    - $R -e "library('Epi')"           # [not win]
    - "\"%R%\" -e \"library('Epi')\""  # [win]

about:
  home: http://BendixCarstensen.com/Epi/
  license: GPL-2.0-only
  summary: "Functions for demographic and epidemiological analysis in the Lexis diagram, i.e. register and cohort follow-up data, in particular representation, manipulation and simulation of multistate  data - the Lexis suite of functions, which includes interfaces to 'mstate', 'etm' and 'cmprsk' packages.  Also contains
    functions for Age-Period-Cohort and Lee-Carter modeling and a function for interval censored data and some useful functions for tabulation and plotting, as well as a number of epidemiological data sets. "
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: Epi
# Version: 2.38
# Date: 2019-08-01
# Title: A Package for Statistical Analysis in Epidemiology
# Authors@R: c(person("Bendix", "Carstensen", role = c("aut", "cre"), email = "b@bxc.dk"), person("Martyn", "Plummer", role = "aut", email = "Martyn.Plummer@warwick.ac.uk"), person("Esa", "Laara", role = "ctb"), person("Michael", "Hills", role = "ctb"))
# Depends: R (>= 3.5.0), utils
# Imports: cmprsk, etm, splines, MASS, survival, plyr, Matrix, numDeriv, data.table, zoo, mgcv
# Suggests: mstate, nlme, lme4, popEpi
# Description: Functions for demographic and epidemiological analysis in the Lexis diagram, i.e. register and cohort follow-up data, in particular representation, manipulation and simulation of multistate  data - the Lexis suite of functions, which includes interfaces to 'mstate', 'etm' and 'cmprsk' packages.  Also contains functions for Age-Period-Cohort and Lee-Carter modeling and a function for interval censored data and some useful functions for tabulation and plotting, as well as a number of epidemiological data sets.
# License: GPL-2
# URL: http://BendixCarstensen.com/Epi/
# NeedsCompilation: yes
# Packaged: 2019-08-06 06:50:31 UTC; bendix
# Author: Bendix Carstensen [aut, cre], Martyn Plummer [aut], Esa Laara [ctb], Michael Hills [ctb]
# Maintainer: Bendix Carstensen <b@bxc.dk>
# Repository: CRAN
# Date/Publication: 2019-08-07 09:10:02 UTC
