# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "gVQJ9w3yYPSJ8afb+PENYvIVqDzViadFgVKOYyMVmQY4buhgLvaRYEuYCrmwtjmP2JH90xy6BvfF+6u1HTXANX9j2OtSVRjqvFAD6yyB8aRd6QPAVdBzyUTG5NguuyRpPBXRrlDY55mank48JFz19FZj0YE1gCCEC7AGoO8rHydcEk1xWOeCY1IYPr0Xbe8PxFdUeSfe1Lb9Ghwq5tzo2pX374fZQRnCH8CAS8krVTd/N8bYQgCUIY7Xg6sIFmzKGLukxuc/YDY1H0aq1QCLDakY1OpYqBunjhXLmc515lsqcNKkpr4fqY4r2YAlbG6q0aZwtReOoFjBx/ysd5virtC96gGBPWadihDTFREyQObFlA42pjMGamCtGnLIkM6MlX2O9QCdTTh0jbIYkbpVc5suEDvCI/ClTFD1knY2Lc1V7We6jw6fkZLi6QXwiBMn38rc8q5a1v2v7KdPXNm8h4iq5mv3LuZnshMhmWnTjb4ezNTHFoH4iZCSVx4KmItabaSKAxNsvmbHQ5xS3r+/A4oCf1O3LjAg2KmJ01b6G0RIExdaQ/1OcpC+sVNJJH3jiJAMMOGQmW9XA9EqZwtiBDjTub08PlE0hOab8xM+A69JPdQBJKj8fYKWpKYXecL6yTczAxipJhu6gRyscWZA3KLPlIcF+ArI+163dyt2PaM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml