appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: gVQJ9w3yYPSJ8afb+PENYvIVqDzViadFgVKOYyMVmQY4buhgLvaRYEuYCrmwtjmP2JH90xy6BvfF+6u1HTXANX9j2OtSVRjqvFAD6yyB8aRd6QPAVdBzyUTG5NguuyRpPBXRrlDY55mank48JFz19FZj0YE1gCCEC7AGoO8rHydcEk1xWOeCY1IYPr0Xbe8PxFdUeSfe1Lb9Ghwq5tzo2pX374fZQRnCH8CAS8krVTd/N8bYQgCUIY7Xg6sIFmzKGLukxuc/YDY1H0aq1QCLDakY1OpYqBunjhXLmc515lsqcNKkpr4fqY4r2YAlbG6q0aZwtReOoFjBx/ysd5virtC96gGBPWadihDTFREyQObFlA42pjMGamCtGnLIkM6MlX2O9QCdTTh0jbIYkbpVc5suEDvCI/ClTFD1knY2Lc1V7We6jw6fkZLi6QXwiBMn38rc8q5a1v2v7KdPXNm8h4iq5mv3LuZnshMhmWnTjb4ezNTHFoH4iZCSVx4KmItabaSKAxNsvmbHQ5xS3r+/A4oCf1O3LjAg2KmJ01b6G0RIExdaQ/1OcpC+sVNJJH3jiJAMMOGQmW9XA9EqZwtiBDjTub08PlE0hOab8xM+A69JPdQBJKj8fYKWpKYXecL6yTczAxipJhu6gRyscWZA3KLPlIcF+ArI+163dyt2PaM=
